# Generated by Django 5.1.4 on 2025-03-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='clinic_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalCRM.clinicbranch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='clinic_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalCRM.clinicroom', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание визита'),
        ),
    ]
