# Generated by Django 5.1.4 on 2025-03-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCRM', '0002_visitrecord_clinic_branch_visitrecord_clinic_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Продолжительность (в минутах)'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='visit_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
    ]
