# Generated by Django 5.1.4 on 2025-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCRM', '0003_visitrecord_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='services',
            field=models.ManyToManyField(blank=True, to='medicalCRM.servicepricelist', verbose_name='Оказанные услуги'),
        ),
    ]
