# Generated by Django 5.1.4 on 2025-03-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCRM', '0004_alter_visitrecord_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='Продолжительность (в минутах)'),
        ),
    ]
