# Generated by Django 5.1.4 on 2025-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCRM', '0005_alter_visitrecord_duration_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepricelist',
            options={'ordering': ['subgroup_number', 'service_code'], 'verbose_name': 'Прайс-лист услуги', 'verbose_name_plural': 'Прайс-лист услуг'},
        ),
        migrations.AddField(
            model_name='servicepricelist',
            name='subgroup_name',
            field=models.CharField(default='Без подгруппы', max_length=255, verbose_name='Название подгруппы'),
        ),
        migrations.AddField(
            model_name='servicepricelist',
            name='subgroup_number',
            field=models.IntegerField(default=0, verbose_name='Номер подгруппы'),
        ),
    ]
