# Generated by Django 5.1.4 on 2025-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCRM', '0006_alter_servicepricelist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepricelist',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена услуги'),
        ),
        migrations.AlterField(
            model_name='servicepricelist',
            name='subgroup_number',
            field=models.CharField(max_length=20, verbose_name='Номер подгруппы'),
        ),
    ]
