# Generated by Django 5.1.4 on 2025-03-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCRM', '0007_alter_servicepricelist_service_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Скидка (%) на визит'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='discounted_services',
            field=models.ManyToManyField(blank=True, related_name='discounted_visits', to='medicalCRM.servicepricelist', verbose_name='Услуги со скидкой'),
        ),
    ]
