# Generated by Django 5.1.4 on 2025-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalCRM', '0008_visitrecord_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='visit_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания визита'),
        ),
    ]
