# Generated by Django 5.1.4 on 2025-02-16 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('lead_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('lead', 'Лид'), ('client', 'Клиент'), ('customer', 'Заказчик')], default='lead', max_length=50)),
                ('manager', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact_1', models.TextField(blank=True, null=True)),
                ('contact_2', models.TextField(blank=True, null=True)),
                ('contact_3', models.TextField(blank=True, null=True)),
                ('contact_4', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_fields', models.JSONField(blank=True, default=list)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='auth.group', verbose_name='Группа с доступом')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=40, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Електронна пошта')),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('lead', 'Лид'), ('client', 'Клиент'), ('customer', 'Заказчик')], default='lead', max_length=50, null=True)),
                ('deal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deal_amount_currency', models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_amount_currency', models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3)),
                ('expected_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_profit_currency', models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3)),
                ('contact', models.CharField(blank=True, choices=[('contact_1', 'Контакт 1'), ('contact_2', 'Контакт 2'), ('contact_3', 'Контакт 3'), ('contact_4', 'Контакт 4')], max_length=10, null=True)),
                ('change_status_contact', models.CharField(blank=True, choices=[('contact_1', 'Контакт 1'), ('contact_2', 'Контакт 2'), ('contact_3', 'Контакт 3'), ('contact_4', 'Контакт 4')], max_length=10, null=True)),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='low', max_length=12, verbose_name='Пріоритет')),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('inquiry_date', models.DateTimeField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manually_updated', models.BooleanField(default=False, verbose_name='Ручное изменение')),
                ('updated_by', models.ManyToManyField(blank=True, related_name='updated_rows', to=settings.AUTH_USER_MODEL, verbose_name='Змінено користувачем')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='clients.customtable')),
            ],
            options={
                'permissions': [('can_update_manually', 'Может изменять manually_updated')],
            },
        ),
    ]
