# Generated by Django 5.1.4 on 2025-01-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_id_client_contact_1_client_contact_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('manager', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('lead', 'Лид'), ('client', 'Клиент'), ('customer', 'Заказчик')], max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('next_step', models.TextField(blank=True, null=True)),
                ('communication_result', models.TextField(blank=True, null=True)),
                ('deal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_1', models.TextField(blank=True, null=True)),
                ('contact_2', models.TextField(blank=True, null=True)),
                ('contact_3', models.TextField(blank=True, null=True)),
                ('contact_4', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('record_date', models.DateField()),
                ('inquiry_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.customtable')),
            ],
        ),
    ]
