# Generated by Django 5.1.4 on 2025-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_customtable_customrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrow',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
