# Generated by Django 5.1.4 on 2025-01-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_customrow_deal_amount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrow',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='communication_result',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='contact_1',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='contact_2',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='contact_3',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='contact_4',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='last_contact',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='next_step',
        ),
        migrations.RemoveField(
            model_name='customrow',
            name='priority',
        ),
        migrations.AddField(
            model_name='customrow',
            name='contact',
            field=models.CharField(blank=True, choices=[('contact_1', 'Контакт 1'), ('contact_2', 'Контакт 2'), ('contact_3', 'Контакт 3'), ('contact_4', 'Контакт 4')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customrow',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customrow',
            name='status',
            field=models.CharField(blank=True, choices=[('lead', 'Лид'), ('client', 'Клиент'), ('customer', 'Заказчик')], default='lead', max_length=50, null=True),
        ),
    ]
