# Generated by Django 5.1.4 on 2025-01-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_customrow_city_remove_customrow_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrow',
            name='change_status_contact',
            field=models.CharField(blank=True, choices=[('contact_1', 'Контакт 1'), ('contact_2', 'Контакт 2'), ('contact_3', 'Контакт 3'), ('contact_4', 'Контакт 4')], max_length=10, null=True),
        ),
    ]
