# Generated by Django 5.1.4 on 2025-01-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_customrow_change_status_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtable',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Країна'),
        ),
    ]
