# Generated by Django 5.1.4 on 2025-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_customtable_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrow',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
