# Generated by Django 5.1.4 on 2025-01-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_customrow_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrow',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
