# Generated by Django 5.1.4 on 2025-01-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_customrow_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtable',
            name='country',
        ),
        migrations.AddField(
            model_name='customrow',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
