# Generated by Django 5.1.4 on 2025-01-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_customtable_country_customrow_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrow',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='low', max_length=12, verbose_name='Пріоритет'),
        ),
    ]
