# Generated by Django 5.1.4 on 2025-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_customrow_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrow',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
    ]
