# Generated by Django 5.1.4 on 2025-01-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_customrow_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrow',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
    ]
