# Generated by Django 5.1.4 on 2025-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_customrow_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtable',
            name='visible_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customrow',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Електронна пошта'),
        ),
    ]
