# Generated by Django 5.1.4 on 2025-01-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_customtable_visible_fields_alter_customrow_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrow',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customrow',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='clients.customtable'),
        ),
    ]
