# Generated by Django 5.1.4 on 2025-01-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_customrow_additional_data_alter_customrow_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrow',
            name='manually_updated',
            field=models.BooleanField(default=False, verbose_name='Ручное изменение'),
        ),
    ]
