# Generated by Django 5.1.4 on 2025-01-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0018_customrow_manually_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='auth.group', verbose_name='Группа с доступом'),
        ),
    ]
