# Generated by Django 5.1.4 on 2025-01-28 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_customtable_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrow',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='customrow',
            name='updated_by',
            field=models.ManyToManyField(blank=True, related_name='updated_rows', to=settings.AUTH_USER_MODEL, verbose_name='Змінено користувачем'),
        ),
    ]
