# Generated by Django 5.1.4 on 2025-02-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_remove_customrow_updated_by_customrow_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrow',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customrow',
            name='inquiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customrow',
            name='record_date',
            field=models.DateTimeField(),
        ),
    ]
