# Generated by Django 5.1.4 on 2025-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_customrow_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrow',
            name='record_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
