# Generated by Django 5.1.4 on 2025-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_alter_customrow_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrow',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customrow',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
