# Generated by Django 5.1.4 on 2025-02-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_customrow_manager_alter_customrow_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrow',
            options={'permissions': [('can_update_manually', 'Может изменять manually_updated')]},
        ),
    ]
